execution_mode: 1
browser: chrome
loader_classname: loading
db_details:
  database: mssql
  db_server: dell-staging.database.windows.net
  db_name: dell-voc-dev
  db_user: gramener
  db_password: kV$4uGC!B
