# """
# execution_mode(mandatory) :
#   1 - will guide the script to execute all the test scripts(.yaml) files available under test scripts folder.
#   2 - test scripts execution is based on the test suite defined. Controlled execution where you can define what to execute and what not to.

#browser_details(mandatory):
# browser(mandatory):
#   browser name(eg. chrome) : launch specific browser to execute the test cases.
#   browsers list([chrome, firefox]) : launch all browsers mentioned in the list parllely to execute the test cases
#   mode(mandatory): 'headless' to launch the browser in headless mode, '#headless' to launch the browser in head mode.

# loader_class(optional): If the loader class name is specified, script will wait till the page loading is completed. If not specified, explicit waits should be added to the test script.

# db_details(optional): Database server and credentials to execute queries.

# All optional parameters should be specified as NA
# """

execution_mode: 1
loader_class: loading
browser_details:
  browser: chrome
  mode: #headless
db_details:
  database: mssql
  db_server: XXXXXX
  db_name: XXXXXX
  db_user: XXXXXX
  db_password: XXXXXX
